name: music_collection
description: An App to organize a collection of Vinyl, CDs and co.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  easy_localization: ^3.0.5
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.5
  equatable: ^2.0.5
  lottie: ^3.1.0
  dio: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.1
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.8.0
  envied: ^0.5.3
  flutter_svg: ^2.0.10+1
  mobile_scanner: ^4.0.1
  image_network: ^2.5.6
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  restart_app: ^1.2.1
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  envied_generator: ^0.5.3


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora-VariableFont_wght.ttf
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf
