name: music_collection
description: An App to organize a collection of Vinyl, CDs and co.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15
  easy_localization: ^3.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^8.0.5
  google_fonts: ^5.1.0
  url_launcher: ^6.1.11
  equatable: ^2.0.5
  lottie: ^2.4.0
  dio: ^5.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.0.0
  dynamic_color: ^1.6.5
  material_color_utilities: ^0.2.0
  envied: ^0.3.0+3
  flutter_svg: ^2.0.7
  mobile_scanner: ^3.2.0
  image_network: ^2.5.4+1
  shared_preferences: ^2.1.2
  flutter_colorpicker: ^1.0.3
  restart_app: ^1.2.1
  flutter_local_notifications: ^14.1.1
  flutter_timezone: ^1.0.6
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  envied_generator: ^0.3.0+3


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora-VariableFont_wght.ttf
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf
