name: music_collection
description: An App to organize a collection of Vinyl, CDs and co.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.14
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  equatable: ^2.0.5
  lottie: ^2.3.2
  dio: ^5.1.1
  bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^0.13.5
  flutter_barcode_scanner: ^2.0.0
  dynamic_color: ^1.6.3
  envied: ^0.3.0
  flutter_svg: ^2.0.5
  mobile_scanner: ^3.2.0
  image_network: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  envied_generator: ^0.3.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
