name: cd_organizer
description: An app to organize CD's by scanning barcodes.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.12
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  go_router: ^6.0.8
  google_fonts: ^4.0.3
  url_launcher: ^6.1.9
  equatable: ^2.0.5
  lottie: ^2.2.0
  dio: ^5.0.0
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true


  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
