name: music_collection
description: An App to organize a collection of Vinyl, CDs and co.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.14
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  get_it: ^7.3.0
  go_router: ^6.5.8
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  equatable: ^2.0.5
  lottie: ^2.3.2
  dio: ^5.1.1
  bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^0.13.5
  flutter_barcode_scanner: ^2.0.0
  dynamic_color: ^1.6.3
  material_color_utilities: ^0.2.0
  envied: ^0.3.0
  flutter_svg: ^2.0.5
  mobile_scanner: ^3.2.0
  image_network: ^2.5.1
  shared_preferences: ^2.1.0
  flutter_colorpicker: ^1.0.3
  restart_app: ^1.1.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  envied_generator: ^0.3.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
