name: music_collection
description: An App to organize a collection of Vinyl, CDs and co.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15
  easy_localization: ^3.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  equatable: ^2.0.5
  lottie: ^2.3.2
  dio: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^0.13.6
  dynamic_color: ^1.6.5
  material_color_utilities: ^0.2.0
  envied: ^0.3.0+3
  flutter_svg: ^2.0.6
  mobile_scanner: ^3.2.0
  image_network: ^2.5.2
  shared_preferences: ^2.1.1
  flutter_colorpicker: ^1.0.3
  restart_app: ^1.2.1
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/
    - assets/translations/

  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora-VariableFont_wght.ttf
